# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Vote.create(name: "월요일 1교시")
Vote.create(name: "화요일 1교시")
Vote.create(name: "수요일 1교시")
Vote.create(name: "목요일 1교시")
Vote.create(name: "금요일 1교시")
Vote.create(name: "월요일 2교시")
Vote.create(name: "화요일 2교시")
Vote.create(name: "수요일 2교시")
Vote.create(name: "목요일 2교시")
Vote.create(name: "금요일 2교시")
Vote.create(name: "월요일 34교시")
Vote.create(name: "화요일 34교시")
Vote.create(name: "수요일 34교시")
Vote.create(name: "목요일 34교시")
Vote.create(name: "금요일 34교시")
Vote.create(name: "월요일 5교시")
Vote.create(name: "화요일 5교시")
Vote.create(name: "수요일 5교시")
Vote.create(name: "목요일 5교시")
Vote.create(name: "금요일 5교시")
Vote.create(name: "월요일 6교시")
Vote.create(name: "화요일 6교시")
Vote.create(name: "수요일 6교시")
Vote.create(name: "목요일 6교시")
Vote.create(name: "금요일 6교시")
Vote.create(name: "월요일 78교시")
Vote.create(name: "화요일 78교시")
Vote.create(name: "수요일 78교시")
Vote.create(name: "목요일 78교시")
Vote.create(name: "금요일 78교시")
Vote.create(name: "월요일 방과후")
Vote.create(name: "화요일 방과후")
Vote.create(name: "수요일 방과후")
Vote.create(name: "목요일 방과후")
Vote.create(name: "금요일 방과후")
